#!/bin/sh
set -eu

if [ "$#" -ne 0 ]; then
	echo "This command does not accept arguments." >&2
	exit 2
fi

export DEBIAN_FRONTEND=noninteractive
/usr/bin/apt-get update
/usr/bin/apt-get upgrade --yes
